export type QuestionTemplate = {
  quizType: "practice" | "certification";
  prompt: string;
  options: string[];
  correctIndex: number;
  explanation?: string;
  category?: string;
  difficulty?: string;
  isCore?: boolean;
};

export type QuizDefaultConfig = {
  practice: { total: number; pointsPerQuestion: number; timeLimitSeconds: number };
  certification: { total: number; pointsPerQuestion: number; timeLimitSeconds: number };
};

export const QUESTION_BANK: Record<string, QuestionTemplate[]> = {
  "Web Development": [
    { quizType: "practice", prompt: "Which HTML tag is used to define a hyperlink?", options: ["<link>", "<a>", "<href>", "<nav>"], correctIndex: 1, explanation: "The <a> (anchor) tag creates hyperlinks.", category: "HTML", difficulty: "easy" },
    { quizType: "practice", prompt: "Which CSS property changes the text color?", options: ["font-color", "text-style", "color", "background-color"], correctIndex: 2, explanation: "The `color` property changes text color.", category: "CSS", difficulty: "easy" },
    { quizType: "practice", prompt: "Which keyword declares a variable in modern JavaScript?", options: ["var", "let", "dim", "set"], correctIndex: 1, category: "JavaScript", difficulty: "easy" },
    { quizType: "practice", prompt: "What does HTML stand for?", options: ["HyperText Markup Language", "HighText Machine Language", "Hyperlink and Text Markup Language", "Home Tool Markup Language"], correctIndex: 0, category: "HTML", difficulty: "easy" },
    { quizType: "practice", prompt: "Which property changes the font of an element in CSS?", options: ["font-family", "text-font", "font-style", "typeface"], correctIndex: 0, category: "CSS", difficulty: "easy" },
    { quizType: "practice", prompt: "Which operator checks strict equality in JavaScript?", options: ["==", "=", "===", "!="], correctIndex: 2, category: "JavaScript", difficulty: "medium" },
    { quizType: "practice", prompt: "Which HTML element is used for the largest heading?", options: ["<heading>", "<h6>", "<head>", "<h1>"], correctIndex: 3, category: "HTML", difficulty: "easy" },
    { quizType: "practice", prompt: "Which array method appends an element to the end?", options: ["push()", "append()", "shift()", "unshift()"], correctIndex: 0, category: "JavaScript", difficulty: "medium" },
    { quizType: "practice", prompt: "Which CSS property controls the space inside an element's border?", options: ["margin", "padding", "spacing", "border-inner"], correctIndex: 1, category: "CSS", difficulty: "easy" },
    { quizType: "practice", prompt: "How do you create a function in JavaScript?", options: ["function myFunc() {}", "def myFunc() {}", "func myFunc() {}", "procedure myFunc() {}"], correctIndex: 0, category: "JavaScript", difficulty: "easy" },
    { quizType: "certification", prompt: "What does HTML stand for?", options: ["HyperText Markup Language", "HighText Machine Language", "Hyperlink and Text Markup Language", "Home Tool Markup Language"], correctIndex: 0, category: "HTML", difficulty: "easy", isCore: true },
    { quizType: "certification", prompt: "Which HTML attribute specifies alternate text for an image?", options: ["src", "alt", "title", "href"], correctIndex: 1, category: "HTML", difficulty: "easy", isCore: true },
    { quizType: "certification", prompt: "Which CSS property controls the space inside an element's border?", options: ["margin", "padding", "spacing", "border-inner"], correctIndex: 1, category: "CSS", difficulty: "easy", isCore: true },
    { quizType: "certification", prompt: "Which is a valid way to declare a function in JavaScript?", options: ["function myFunc() {}", "def myFunc() {}", "func myFunc() {}", "procedure myFunc() {}"], correctIndex: 0, category: "JavaScript", difficulty: "easy", isCore: true },
    { quizType: "certification", prompt: "Which CSS syntax makes all paragraphs bold?", options: ["p {font-weight: bold;}", "<p style='bold'>", "p {text-bold: yes;}", "paragraph {bold: true;}"], correctIndex: 0, category: "CSS", difficulty: "medium", isCore: true },
    { quizType: "certification", prompt: "Which JavaScript method converts a string to a number?", options: ["Number()", "toString()", "String()", "parseString()"], correctIndex: 0, category: "JavaScript", difficulty: "medium", isCore: true },
    { quizType: "certification", prompt: "Which HTML element is used for a line break?", options: ["<break>", "<br>", "<lb>", "<newline>"], correctIndex: 1, category: "HTML", difficulty: "easy" },
    { quizType: "certification", prompt: "Which property makes text bold in CSS?", options: ["text-style", "font-weight", "font-bold", "bold"], correctIndex: 1, category: "CSS", difficulty: "easy" },
    { quizType: "certification", prompt: "What is the output of typeof null in JavaScript?", options: ["'null'", "'object'", "'undefined'", "'number'"], correctIndex: 1, category: "JavaScript", difficulty: "medium" },
    { quizType: "certification", prompt: "Which HTML form element creates a drop-down list?", options: ["<select>", "<dropdown>", "<list>", "<option>"], correctIndex: 0, category: "HTML", difficulty: "medium" },
    { quizType: "certification", prompt: "Which CSS position is relative to the viewport?", options: ["relative", "static", "fixed", "sticky"], correctIndex: 2, category: "CSS", difficulty: "medium" },
    { quizType: "certification", prompt: "Which array method creates a new array from a transform on every element?", options: ["map()", "filter()", "reduce()", "forEach()"], correctIndex: 0, category: "JavaScript", difficulty: "hard" },
    { quizType: "practice", prompt: "Which HTTP status code means 'Not Found'?", options: ["200", "301", "404", "500"], correctIndex: 2, category: "HTTP", difficulty: "easy" },
    { quizType: "practice", prompt: "What does `localStorage` store?", options: ["Data with no expiration", "Session-only data", "Cookies only", "Server cache"], correctIndex: 0, category: "JavaScript", difficulty: "medium" },
    { quizType: "practice", prompt: "Which element is used to embed JavaScript?", options: ["<script>", "<js>", "<code>", "<style>"], correctIndex: 0, category: "JavaScript", difficulty: "easy" },
    { quizType: "practice", prompt: "Which property hides an element but keeps layout space?", options: ["display: none", "visibility: hidden", "opacity: 0", "position: static"], correctIndex: 1, category: "CSS", difficulty: "medium" },
    { quizType: "practice", prompt: "What does CSS stand for?", options: ["Cascading Style Sheets", "Computer Style Sheets", "Creative Style System", "Cascading Sheet System"], correctIndex: 0, category: "CSS", difficulty: "easy" },
    { quizType: "practice", prompt: "Which method removes the last element from an array?", options: ["pop()", "shift()", "splice()", "slice()"], correctIndex: 0, category: "JavaScript", difficulty: "medium" },
    { quizType: "practice", prompt: "Which HTML attribute makes an input required?", options: ["required", "mandatory", "needed", "must"], correctIndex: 0, category: "HTML", difficulty: "easy" },
    { quizType: "practice", prompt: "Which HTTP method is used to update a resource?", options: ["GET", "POST", "PUT", "DELETE"], correctIndex: 2, category: "HTTP", difficulty: "medium" },
    { quizType: "practice", prompt: "What is the default display value of a `<div>`?", options: ["block", "inline", "flex", "grid"], correctIndex: 0, category: "HTML", difficulty: "easy" },
    { quizType: "certification", prompt: "Which HTTP status code means 'Internal Server Error'?", options: ["400", "404", "500", "302"], correctIndex: 2, category: "HTTP", difficulty: "medium", isCore: true },
    { quizType: "certification", prompt: "Which method converts an array to a string?", options: ["join()", "concat()", "map()", "reverse()"], correctIndex: 0, category: "JavaScript", difficulty: "medium", isCore: true },
    { quizType: "certification", prompt: "Which CSS unit is relative to the root font size?", options: ["rem", "em", "px", "vh"], correctIndex: 0, category: "CSS", difficulty: "medium", isCore: true },
    { quizType: "certification", prompt: "Which box-sizing value includes padding in an element's width?", options: ["border-box", "content-box", "padding-box", "inherit"], correctIndex: 0, category: "CSS", difficulty: "medium", isCore: true },
    { quizType: "certification", prompt: "Which HTML element defines navigation links?", options: ["<nav>", "<header>", "<footer>", "<aside>"], correctIndex: 0, category: "HTML", difficulty: "easy" },
    { quizType: "certification", prompt: "What does the `const` keyword mean in JavaScript?", options: ["A non-reassignable variable binding", "A variable that can be reassigned", "A function declaration", "A CSS selector"], correctIndex: 0, category: "JavaScript", difficulty: "easy" },
    { quizType: "certification", prompt: "Which tool is commonly used to manage front-end packages?", options: ["npm", "pip", "Maven", "Composer"], correctIndex: 0, category: "Tooling", difficulty: "medium" },
    { quizType: "certification", prompt: "Which HTTP method is considered safe and idempotent for retrieving a resource?", options: ["GET", "POST", "DELETE", "PUT"], correctIndex: 0, category: "HTTP", difficulty: "medium" },
    { quizType: "certification", prompt: "Which property sets the space between a flex container's items on the main axis?", options: ["gap", "padding", "margin", "spacing"], correctIndex: 0, category: "CSS", difficulty: "hard" },
    { quizType: "certification", prompt: "Which `<form>` method sends data in the URL?", options: ["GET", "POST", "PUT", "SEND"], correctIndex: 0, category: "HTML", difficulty: "medium" },
    { quizType: "certification", prompt: "Which regular expression anchor matches the start of a string?", options: ["^", "$", "\\b", "."], correctIndex: 0, category: "JavaScript", difficulty: "hard" },
    { quizType: "certification", prompt: "Which set of styles is applied when the viewport is small?", options: ["Media queries", "Inline styles", "External links", "CSS variables"], correctIndex: 0, category: "CSS", difficulty: "medium" },
  ],
  "UI/UX Design": [
    { quizType: "practice", prompt: "What does UX stand for?", options: ["User Exchange", "User Experience", "Universal Experience", "User Execution"], correctIndex: 1, category: "Fundamentals", difficulty: "easy" },
    { quizType: "practice", prompt: "What is the primary goal of a wireframe?", options: ["Final visual design", "Structure and layout planning", "Color scheme selection", "Font pairing"], correctIndex: 1, category: "Process", difficulty: "easy" },
    { quizType: "practice", prompt: "Which principle refers to contrast between two elements?", options: ["Proximity", "Alignment", "Contrast", "Hierarchy"], correctIndex: 2, category: "Design Principles", difficulty: "easy" },
    { quizType: "practice", prompt: "What does UI stand for?", options: ["User Interface", "User Integration", "Universal Interface", "User Interaction"], correctIndex: 0, category: "Fundamentals", difficulty: "easy" },
    { quizType: "practice", prompt: "What is a 'persona' in UX design?", options: ["A fictional character representing a user group", "The designer's avatar", "A type of wireframe", "A CSS selector"], correctIndex: 0, category: "Research", difficulty: "medium" },
    { quizType: "practice", prompt: "Which color model is primarily used on screens?", options: ["CMYK", "RGB", "RYB", "Pantone"], correctIndex: 1, category: "Visual Design", difficulty: "medium" },
    { quizType: "practice", prompt: "What is a user flow?", options: ["The path a user takes to complete a task", "A CSS animation", "A type of grid system", "A color palette"], correctIndex: 0, category: "Research", difficulty: "medium" },
    { quizType: "practice", prompt: "Which principle groups related items together?", options: ["Proximity", "Contrast", "Repetition", "White space"], correctIndex: 0, category: "Design Principles", difficulty: "easy" },
    { quizType: "certification", prompt: "What does UX stand for?", options: ["User Exchange", "User Experience", "Universal Experience", "User Execution"], correctIndex: 1, category: "Fundamentals", difficulty: "easy", isCore: true },
    { quizType: "certification", prompt: "What does UI stand for?", options: ["User Interface", "User Integration", "Universal Interface", "User Interaction"], correctIndex: 0, category: "Fundamentals", difficulty: "easy", isCore: true },
    { quizType: "certification", prompt: "What is the primary goal of a wireframe?", options: ["Final visual design", "Structure and layout planning", "Color scheme selection", "Font pairing"], correctIndex: 1, category: "Process", difficulty: "easy", isCore: true },
    { quizType: "certification", prompt: "Which principle refers to the visual weight balance of elements?", options: ["Balance", "Proximity", "Rhythm", "Contrast"], correctIndex: 0, category: "Design Principles", difficulty: "easy", isCore: true },
    { quizType: "certification", prompt: "What is a 'user flow'?", options: ["The path a user takes to complete a task", "A CSS animation", "A type of grid system", "A color palette"], correctIndex: 0, category: "Research", difficulty: "medium", isCore: true },
    { quizType: "certification", prompt: "Which principle involves grouping related items together?", options: ["Proximity", "Contrast", "Repetition", "White space"], correctIndex: 0, category: "Design Principles", difficulty: "medium", isCore: true },
    { quizType: "certification", prompt: "What does 'heuristic evaluation' involve?", options: ["Expert review against usability principles", "User interviews", "A/B testing", "Eye tracking"], correctIndex: 0, category: "Usability", difficulty: "medium" },
    { quizType: "certification", prompt: "Which color model is used for print?", options: ["RGB", "CMYK", "HSL", "HEX"], correctIndex: 1, category: "Visual Design", difficulty: "medium" },
    { quizType: "certification", prompt: "What is a 'wireframe' primarily used for?", options: ["Planning layout without visual design", "Final branding", "Font selection", "Color grading"], correctIndex: 0, category: "Process", difficulty: "easy" },
    { quizType: "practice", prompt: "What is an 'affordance' in UI design?", options: ["A property that suggests how an element can be used", "A type of grid", "A color palette", "A user story"], correctIndex: 0, category: "Foundations", difficulty: "easy" },
    { quizType: "practice", prompt: "What is the purpose of a style guide?", options: ["To keep design consistent across a product", "To store user passwords", "To schedule sprints", "To run A/B tests"], correctIndex: 0, category: "Process", difficulty: "easy" },
    { quizType: "practice", prompt: "Which principle reduces cognitive load by removing unnecessary elements?", options: ["simplicity", "decoration", "complexity", "contrast"], correctIndex: 0, category: "Design Principles", difficulty: "medium" },
    { quizType: "practice", prompt: "What does 'white space' improve?", options: ["Readability and visual balance", "Page load speed", "Font size", "Bandwidth"], correctIndex: 0, category: "Visual Design", difficulty: "easy" },
    { quizType: "practice", prompt: "Which technique tests a design with real users?", options: ["Usability testing", "Heuristic review only", "Wireframing", "Mood boarding"], correctIndex: 0, category: "Research", difficulty: "easy" },
    { quizType: "practice", prompt: "What is the purpose of a prototype?", options: ["To test interactions before final build", "To replace the database", "To set pricing", "To write copy"], correctIndex: 0, category: "Process", difficulty: "easy" },
    { quizType: "practice", prompt: "Which color combination generally offers the highest contrast?", options: ["Dark text on light background", "Red on orange", "Blue on purple", "Yellow on white"], correctIndex: 0, category: "Accessibility", difficulty: "medium" },
    { quizType: "practice", prompt: "What does a 'sitemap' show?", options: ["The structure and hierarchy of pages", "The visual theme", "The font stack", "The color palette"], correctIndex: 0, category: "Architecture", difficulty: "medium" },
    { quizType: "practice", prompt: "Which tool is used to build accessible color palettes?", options: ["Contrast checkers", "Font loaders", "Image editors only", "Animation tools"], correctIndex: 0, category: "Accessibility", difficulty: "easy" },
    { quizType: "certification", prompt: "What is an 'affordance' in UI design?", options: ["A property that suggests how an element can be used", "A type of grid", "A color palette", "A user story"], correctIndex: 0, category: "Foundations", difficulty: "easy", isCore: true },
    { quizType: "certification", prompt: "Which principle reduces cognitive load by removing unnecessary elements?", options: ["simplicity", "decoration", "complexity", "contrast"], correctIndex: 0, category: "Design Principles", difficulty: "medium", isCore: true },
    { quizType: "certification", prompt: "What does 'white space' improve?", options: ["Readability and visual balance", "Page load speed", "Font size", "Bandwidth"], correctIndex: 0, category: "Visual Design", difficulty: "easy", isCore: true },
    { quizType: "certification", prompt: "What is the purpose of a prototype?", options: ["To test interactions before final build", "To replace the database", "To set pricing", "To write copy"], correctIndex: 0, category: "Process", difficulty: "easy", isCore: true },
    { quizType: "certification", prompt: "Which color combination offers the highest contrast and readability?", options: ["Dark text on light background", "Red on orange", "Blue on purple", "Yellow on white"], correctIndex: 0, category: "Accessibility", difficulty: "medium", isCore: true },
    { quizType: "certification", prompt: "What does a 'sitemap' show?", options: ["The structure and hierarchy of pages", "The visual theme", "The font stack", "The color palette"], correctIndex: 0, category: "Architecture", difficulty: "medium", isCore: true },
    { quizType: "certification", prompt: "Which approach tests a design with real end users?", options: ["Usability testing", "Heuristic review only", "Wireframing", "Mood boarding"], correctIndex: 0, category: "Research", difficulty: "easy" },
    { quizType: "certification", prompt: "What is the primary purpose of a style guide?", options: ["Ensuring consistent visual design", "Storing user data", "Compiling code", "Scheduling releases"], correctIndex: 0, category: "Process", difficulty: "easy" },
    { quizType: "certification", prompt: "Which contrast ratio is commonly targeted for normal text (WCAG AA)?", options: ["4.5:1", "1:1", "2:1", "0.5:1"], correctIndex: 0, category: "Accessibility", difficulty: "hard" },
    { quizType: "certification", prompt: "What does 'accessibility' primarily ensure?", options: ["Products usable by people with varied abilities", "Faster load times", "More colors", "Smaller files"], correctIndex: 0, category: "Accessibility", difficulty: "easy" },
    { quizType: "certification", prompt: "Which element helps order a page's visual hierarchy?", options: ["Size and spacing", "File extension", "Domain name", "Server type"], correctIndex: 0, category: "Design Principles", difficulty: "medium" },
  ],
  "Machine Learning": [
    { quizType: "practice", prompt: "Which type of learning uses labeled data?", options: ["Supervised", "Unsupervised", "Reinforcement", "Semi-random"], correctIndex: 0, category: "Fundamentals", difficulty: "easy" },
    { quizType: "practice", prompt: "What does ML stand for?", options: ["Machine Learning", "Marketing Logic", "Model Language", "Meta Learning"], correctIndex: 0, category: "Fundamentals", difficulty: "easy" },
    { quizType: "practice", prompt: "Which algorithm is used for classification?", options: ["Logistic Regression", "K-Means", "PCA", "Apriori"], correctIndex: 0, category: "Algorithms", difficulty: "medium" },
    { quizType: "practice", prompt: "What is overfitting?", options: ["Model learns training data too well, hurting generalization", "Model performs poorly on training data", "Model trains too fast", "Model has too few features"], correctIndex: 0, category: "Training", difficulty: "medium" },
    { quizType: "practice", prompt: "Which is an unsupervised learning algorithm?", options: ["K-Means clustering", "Linear Regression", "Logistic Regression", "Decision Tree classifier"], correctIndex: 0, category: "Algorithms", difficulty: "medium" },
    { quizType: "practice", prompt: "What does 'feature' mean in ML?", options: ["An individual measurable property of a data point", "A model output", "A loss function", "A neural layer"], correctIndex: 0, category: "Fundamentals", difficulty: "easy" },
    { quizType: "certification", prompt: "Which type of learning uses labeled data?", options: ["Supervised", "Unsupervised", "Reinforcement", "Semi-random"], correctIndex: 0, category: "Fundamentals", difficulty: "easy", isCore: true },
    { quizType: "certification", prompt: "What does ML stand for?", options: ["Machine Learning", "Marketing Logic", "Model Language", "Meta Learning"], correctIndex: 0, category: "Fundamentals", difficulty: "easy", isCore: true },
    { quizType: "certification", prompt: "Which algorithm is used for classification?", options: ["Logistic Regression", "K-Means", "PCA", "Apriori"], correctIndex: 0, category: "Algorithms", difficulty: "medium", isCore: true },
    { quizType: "certification", prompt: "What is overfitting?", options: ["Model learns training data too well, hurting generalization", "Model performs poorly on training data", "Model trains too fast", "Model has too few features"], correctIndex: 0, category: "Training", difficulty: "medium", isCore: true },
    { quizType: "certification", prompt: "Which is an unsupervised learning algorithm?", options: ["K-Means clustering", "Linear Regression", "Logistic Regression", "Decision Tree classifier"], correctIndex: 0, category: "Algorithms", difficulty: "medium", isCore: true },
    { quizType: "certification", prompt: "What is the goal of regression?", options: ["Predict a continuous value", "Group similar items", "Reduce dimensions", "Classify categories"], correctIndex: 0, category: "Algorithms", difficulty: "medium", isCore: true },
    { quizType: "certification", prompt: "What does a loss function measure?", options: ["The difference between predictions and true values", "The model's speed", "The dataset size", "The number of features"], correctIndex: 0, category: "Training", difficulty: "medium" },
    { quizType: "certification", prompt: "What is a neural network composed of?", options: ["Layers of interconnected neurons", "Decision trees only", "Clusters only", "Rules only"], correctIndex: 0, category: "Deep Learning", difficulty: "easy" },
    { quizType: "practice", prompt: "Which step prepares raw data for modeling?", options: ["Preprocessing", "Deploying", "Labeling images", "Training only"], correctIndex: 0, category: "Process", difficulty: "easy" },
    { quizType: "practice", prompt: "What is a hyperparameter?", options: ["A setting configured before training", "An output label", "A training sample", "A loss value"], correctIndex: 0, category: "Training", difficulty: "medium" },
    { quizType: "practice", prompt: "Which metric measures the fraction of correct predictions?", options: ["Accuracy", "Latency", "Throughput", "Loss-only"], correctIndex: 0, category: "Evaluation", difficulty: "easy" },
    { quizType: "practice", prompt: "Which is a common activation function?", options: ["ReLU", "WHERE", "JOIN", "SUM"], correctIndex: 0, category: "Deep Learning", difficulty: "medium" },
    { quizType: "practice", prompt: "What does 'cross-validation' do?", options: ["Evaluates performance across multiple data splits", "Duplicates the dataset", "Saves checkpoints", "Shuffles labels"], correctIndex: 0, category: "Evaluation", difficulty: "medium" },
    { quizType: "practice", prompt: "Which technique handles data with many missing values?", options: ["Imputation", "Overfitting", "Augmentation", "Pruning"], correctIndex: 0, category: "Process", difficulty: "medium" },
    { quizType: "practice", prompt: "What is 'feature engineering'?", options: ["Selecting and transforming inputs to improve models", "Deleting outputs", "Increasing epochs", "Changing the batch size"], correctIndex: 0, category: "Fundamentals", difficulty: "easy" },
    { quizType: "practice", prompt: "Which type of model is used to predict a category label?", options: ["Classifier", "Regression-only", "Clustering-only", "Autoencoder-only"], correctIndex: 0, category: "Algorithms", difficulty: "easy" },
    { quizType: "practice", prompt: "What is the role of a training set?", options: ["Teaches the model patterns", "Tests deployment", "Stores passwords", "Compiles code"], correctIndex: 0, category: "Training", difficulty: "easy" },
    { quizType: "practice", prompt: "Which reduces overfitting by penalizing large weights?", options: ["Regularization", "Augmentation", "Padding", "Batch norm only"], correctIndex: 0, category: "Training", difficulty: "hard" },
    { quizType: "practice", prompt: "What does 'epoch' mean in training?", options: ["One full pass over the training data", "A single prediction", "A loss value", "A gradient step only"], correctIndex: 0, category: "Training", difficulty: "easy" },
    { quizType: "certification", prompt: "Which step prepares raw data for modeling?", options: ["Preprocessing", "Deploying", "Labeling images", "Training only"], correctIndex: 0, category: "Process", difficulty: "easy", isCore: true },
    { quizType: "certification", prompt: "What is a hyperparameter?", options: ["A setting configured before training", "An output label", "A training sample", "A loss value"], correctIndex: 0, category: "Training", difficulty: "medium", isCore: true },
    { quizType: "certification", prompt: "Which metric measures the fraction of correct predictions?", options: ["Accuracy", "Latency", "Throughput", "Loss-only"], correctIndex: 0, category: "Evaluation", difficulty: "easy", isCore: true },
    { quizType: "certification", prompt: "Which is a common activation function in neural networks?", options: ["ReLU", "WHERE", "JOIN", "SUM"], correctIndex: 0, category: "Deep Learning", difficulty: "medium", isCore: true },
    { quizType: "certification", prompt: "What does 'cross-validation' do?", options: ["Evaluates performance across multiple data splits", "Duplicates the dataset", "Saves checkpoints", "Shuffles labels"], correctIndex: 0, category: "Evaluation", difficulty: "medium", isCore: true },
    { quizType: "certification", prompt: "What is 'feature engineering'?", options: ["Selecting and transforming inputs to improve models", "Deleting outputs", "Increasing epochs", "Changing the batch size"], correctIndex: 0, category: "Fundamentals", difficulty: "medium" },
    { quizType: "certification", prompt: "Which technique handles many missing values in a dataset?", options: ["Imputation", "Overfitting", "Augmentation", "Pruning"], correctIndex: 0, category: "Process", difficulty: "medium" },
    { quizType: "certification", prompt: "What is the purpose of a validation set?", options: ["To tune and evaluate the model during training", "To store prod data", "To run the web UI", "To archive checkpoints"], correctIndex: 0, category: "Training", difficulty: "medium" },
    { quizType: "certification", prompt: "Which concept helps reduce overfitting?", options: ["Regularization", "Larger weights", "Removing data", "Higher epochs only"], correctIndex: 0, category: "Training", difficulty: "hard" },
    { quizType: "certification", prompt: "Which model type predicts a continuous value?", options: ["Regression", "Classification-only", "Clustering", "Autoencoder"], correctIndex: 0, category: "Algorithms", difficulty: "easy" },
  ],
  "Data Analytics": [
    { quizType: "practice", prompt: "Which SQL clause filters rows?", options: ["WHERE", "SELECT", "ORDER BY", "GROUP BY"], correctIndex: 0, category: "SQL", difficulty: "easy" },
    { quizType: "practice", prompt: "What does ETL stand for?", options: ["Extract, Transform, Load", "Edit, Test, Launch", "Evaluate, Transfer, Log", "Empty, Trim, List"], correctIndex: 0, category: "Process", difficulty: "medium" },
    { quizType: "practice", prompt: "Which chart best shows a trend over time?", options: ["Line chart", "Pie chart", "Scatter pie", "Donut chart"], correctIndex: 0, category: "Visualization", difficulty: "easy" },
    { quizType: "practice", prompt: "What is the mean of the dataset [2, 4, 6]?", options: ["4", "2", "6", "12"], correctIndex: 0, category: "Statistics", difficulty: "easy" },
    { quizType: "practice", prompt: "Which SQL keyword returns unique values?", options: ["DISTINCT", "UNIQUE", "FILTER", "SEPARATE"], correctIndex: 0, category: "SQL", difficulty: "medium" },
    { quizType: "practice", prompt: "What does a pivot table do?", options: ["Summarizes and aggregates tabular data", "Deletes data", "Creates random data", "Sorts alphabetically only"], correctIndex: 0, category: "Analysis", difficulty: "medium" },
    { quizType: "certification", prompt: "Which SQL clause filters rows?", options: ["WHERE", "SELECT", "ORDER BY", "GROUP BY"], correctIndex: 0, category: "SQL", difficulty: "easy", isCore: true },
    { quizType: "certification", prompt: "What does ETL stand for?", options: ["Extract, Transform, Load", "Edit, Test, Launch", "Evaluate, Transfer, Log", "Empty, Trim, List"], correctIndex: 0, category: "Process", difficulty: "medium", isCore: true },
    { quizType: "certification", prompt: "Which chart best shows a trend over time?", options: ["Line chart", "Pie chart", "Scatter pie", "Donut chart"], correctIndex: 0, category: "Visualization", difficulty: "easy", isCore: true },
    { quizType: "certification", prompt: "What is the median of [1, 3, 9, 15, 20]?", options: ["9", "3", "15", "48"], correctIndex: 0, category: "Statistics", difficulty: "medium", isCore: true },
    { quizType: "certification", prompt: "Which SQL keyword returns unique values?", options: ["DISTINCT", "UNIQUE", "FILTER", "SEPARATE"], correctIndex: 0, category: "SQL", difficulty: "medium", isCore: true },
    { quizType: "certification", prompt: "What is a dashboard primarily used for?", options: ["Visualizing KPIs at a glance", "Storing raw files", "Writing code", "Backing up data"], correctIndex: 0, category: "Visualization", difficulty: "easy", isCore: true },
    { quizType: "certification", prompt: "Which aggregate function returns the average?", options: ["AVG()", "SUM()", "COUNT()", "MEAN()"], correctIndex: 0, category: "SQL", difficulty: "easy" },
    { quizType: "certification", prompt: "What does a scatter plot best reveal?", options: ["Correlation between two variables", "A single total", "A category count", "A text word count"], correctIndex: 0, category: "Visualization", difficulty: "medium" },
    { quizType: "practice", prompt: "Which SQL clause groups rows by a column?", options: ["GROUP BY", "ORDER BY", "WHERE", "SELECT"], correctIndex: 0, category: "SQL", difficulty: "medium" },
    { quizType: "practice", prompt: "What does a left join return?", options: ["All rows from the left table plus matches", "Only matching rows", "Only the right table", "A cartesian product"], correctIndex: 0, category: "SQL", difficulty: "medium" },
    { quizType: "practice", prompt: "Which statistical term is a measure of spread?", options: ["Standard deviation", "Mean", "Median", "Mode"], correctIndex: 0, category: "Statistics", difficulty: "medium" },
    { quizType: "practice", prompt: "What is a primary key in a relational database?", options: ["A unique identifier for a row", "A foreign reference", "A sort key", "An index-only value"], correctIndex: 0, category: "SQL", difficulty: "easy" },
    { quizType: "practice", prompt: "Which visualization is best for parts of a whole?", options: ["Pie chart", "Line chart", "Bar chart", "Scatter plot"], correctIndex: 0, category: "Visualization", difficulty: "easy" },
    { quizType: "practice", prompt: "What does a bar chart best compare?", options: ["Categories across values", "Trend over time only", "Correlation", "Distribution of raw points"], correctIndex: 0, category: "Visualization", difficulty: "easy" },
    { quizType: "practice", prompt: "Which SQL clause sorts results?", options: ["ORDER BY", "GROUP BY", "HAVING", "JOIN"], correctIndex: 0, category: "SQL", difficulty: "easy" },
    { quizType: "practice", prompt: "What is an outlier?", options: ["A value far from the rest of the data", "The most frequent value", "The average value", "A missing cell"], correctIndex: 0, category: "Statistics", difficulty: "medium" },
    { quizType: "practice", prompt: "Which tool is commonly used for data visualization?", options: ["Tableau", "A text editor only", "A compiler", "A terminal"], correctIndex: 0, category: "Tooling", difficulty: "easy" },
    { quizType: "certification", prompt: "Which SQL clause groups rows by a column?", options: ["GROUP BY", "ORDER BY", "WHERE", "SELECT"], correctIndex: 0, category: "SQL", difficulty: "medium", isCore: true },
    { quizType: "certification", prompt: "What does a left join return?", options: ["All rows from the left table plus matches", "Only matching rows", "Only the right table", "A cartesian product"], correctIndex: 0, category: "SQL", difficulty: "medium", isCore: true },
    { quizType: "certification", prompt: "Which statistical term measures spread?", options: ["Standard deviation", "Mean", "Median", "Mode"], correctIndex: 0, category: "Statistics", difficulty: "medium", isCore: true },
    { quizType: "certification", prompt: "What is a primary key in a relational database?", options: ["A unique identifier for a row", "A foreign reference", "A sort key", "An index-only value"], correctIndex: 0, category: "SQL", difficulty: "easy", isCore: true },
    { quizType: "certification", prompt: "Which visualization is best for parts of a whole?", options: ["Pie chart", "Line chart", "Bar chart", "Scatter plot"], correctIndex: 0, category: "Visualization", difficulty: "easy", isCore: true },
    { quizType: "certification", prompt: "Which SQL clause sorts results?", options: ["ORDER BY", "GROUP BY", "HAVING", "JOIN"], correctIndex: 0, category: "SQL", difficulty: "easy" },
    { quizType: "certification", prompt: "What is an outlier in a dataset?", options: ["A value far from the rest of the data", "The most frequent value", "The average value", "A missing cell"], correctIndex: 0, category: "Statistics", difficulty: "medium" },
    { quizType: "certification", prompt: "Which chart type shows the distribution of a single continuous variable?", options: ["Histogram", "Pie chart", "Scatter plot", "Line chart"], correctIndex: 0, category: "Visualization", difficulty: "medium" },
    { quizType: "certification", prompt: "Which SQL statement removes a table entirely?", options: ["DROP TABLE", "DELETE FROM", "TRUNCATE ROWS", "REMOVE TABLE"], correctIndex: 0, category: "SQL", difficulty: "medium" },
    { quizType: "certification", prompt: "What is data normalization mainly used for?", options: ["Reducing redundancy and improving consistency", "Deleting all data", "Increasing size", "Speeding up typing"], correctIndex: 0, category: "Process", difficulty: "medium" },
  ],
};

export const QUIZ_DEFAULTS_BY_CATEGORY: Record<string, QuizDefaultConfig> = {
  "Web Development": { practice: { total: 8, pointsPerQuestion: 2, timeLimitSeconds: 480 }, certification: { total: 10, pointsPerQuestion: 3, timeLimitSeconds: 600 } },
  "UI/UX Design": { practice: { total: 6, pointsPerQuestion: 2, timeLimitSeconds: 360 }, certification: { total: 8, pointsPerQuestion: 3, timeLimitSeconds: 480 } },
  "Machine Learning": { practice: { total: 6, pointsPerQuestion: 2, timeLimitSeconds: 360 }, certification: { total: 8, pointsPerQuestion: 3, timeLimitSeconds: 480 } },
  "Data Analytics": { practice: { total: 6, pointsPerQuestion: 2, timeLimitSeconds: 360 }, certification: { total: 8, pointsPerQuestion: 3, timeLimitSeconds: 480 } },
};

export function resolveCategory(courseId: string, courseCategory?: string): string {
  if (courseCategory && QUESTION_BANK[courseCategory]) return courseCategory;
  if (courseId.startsWith("web")) return "Web Development";
  if (courseId.startsWith("ui") || courseId.startsWith("ux")) return "UI/UX Design";
  if (courseId.startsWith("machine") || courseId.startsWith("ml")) return "Machine Learning";
  if (courseId.startsWith("data")) return "Data Analytics";
  return "Web Development";
}
